# mosquitto/config/mosquitto.conf
# -------------------------------------------------------------------------
# Hardened Mosquitto Configuration - TLS and Authenticated listeners
# -------------------------------------------------------------------------

# Internal listener (No TLS, restricted within docker internal bridge network)
listener 1883 0.0.0.0

# External listener (TLS Encrypted, exposed to physical ESP32 devices)
listener 8883 0.0.0.0
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key

# Authentication configuration
allow_anonymous false
password_file /mosquitto/config/passwdس
