# docker-compose.yml
services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0.18
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "8883:8883" # Secure MQTTS Port exposed
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/certs:/mosquitto/certs # Mount certificates folder
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:2.15.0-pg16
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=wastebin
      - POSTGRES_USER=wastebin_app
      - POSTGRES_PASSWORD=securepassword
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  ingestion-service:
    build: ./backend/ingestion-service
    container_name: ingestion-service
    environment:
      - MQTT_BROKER=mqtt-broker
      - MQTT_USER=ingestion_service
      - MQTT_PASSWORD=secure_ingestion_pass_2026
      - REDIS_HOST=redis
    depends_on:
      - mqtt-broker
      - redis
    restart: unless-stopped

  fill-estimation-service:
    build: ./backend/fill-estimation-service
    container_name: fill-estimation-service
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: unless-stopped

  persistence-service:
    build: ./backend/persistence-service
    container_name: persistence-service
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://wastebin_app:securepassword@timescaledb:5432/wastebin
    depends_on:
      - redis
      - timescaledb
    restart: unless-stopped

  alerting-service:
    build: ./backend/alerting-service
    container_name: alerting-service
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://wastebin_app:securepassword@timescaledb:5432/wastebin
    depends_on:
      - redis
      - timescaledb
    restart: unless-stopped

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://wastebin_app:securepassword@timescaledb:5432/wastebin
    depends_on:
      - timescaledb
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend-dashboard
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    restart: unless-stopped

volumes:
  timescale_data:
